### ISSUE TITLE
Исправление багов и предложения

### ISSUE THREAD

**Issue by TonyCooT** [clever0ne/laser_rangefinder#1]
Доброго времени суток!

### Ошибка при создании графика
При тестах с моими исходными данными (см. приложение) в файле **print_hystogram.m** возникла ошибка в функции **axis** 
```jsx
    figure('Name', 'Hystogram');
    plot(t, p1, 'r-', t, p2, 'b--');
    axis([tmin, tmax, 0, round(105 * max([p1', p2'])) / 100]);
    grid on;
```
_Value must be a 1x2 vector of numeric type in which the second element is greater than the first element or is Inf._
 
В данном случае используется запись **axis([xmin xmax ymin ymax])**. Вероятно, что ошибка происходит при **ymax <= ymin** или **round(105 * max([p1', p2'])) / 100] <= 0**, т.е. функция **round** возвращает 0.
 
Предлагаю решение в виде масштабного коэффициента

```jsx
    figure('Name', 'Hystogram');
    plot(t, p1, 'r-', t, p2, 'b--');
    axis([tmin, tmax, 0, 1.1 * max([p1', p2'])]);
    grid on;
```
Аналогичное исправление в файле **print_cumulative_distribution_graph.m**

```jsx
    figure('Name', 'Empirical Cumulative Distribution Function');
    plot(t, f1, 'r-', t, f2, 'b--');
    axis([tmin, tmax, 0, 1.1 * max([f1', f2'])]);
    grid on;
```
Приложение: [alpha.txt](https://github.com/clever0ne/laser_rangefinder/files/7354764/alpha.txt), [input.txt](https://github.com/clever0ne/laser_rangefinder/files/7354762/input.txt)
 
### Ошибка при подсчете статистики Колмогорова
 
Исходный код в файле **check_kolmogorov_criterion.m**
 
```jsx
    dn = max(abs(f1 - f2));
    lambda_1 = (6 * n * dn + 1) / (sqrt(6) * n);
    lambda_2 = sqrt(-log(alpha / 2) / 2);
```
Оригинальная формула статистики Колмогорова с поправкой Большева

![image](https://user-images.githubusercontent.com/55048058/137524035-eacdf149-c1e4-44bb-adbf-fbfc0a73ad00.png)

В соответствии с формулой код необходимо привести к следующему виду

```jsx
    dn = max(abs(f1 - f2));
    lambda_1 = (6 * n * dn + 1) / (6 * sqrt(n));
    lambda_2 = sqrt(-log(alpha / 2) / 2);
```
### Точность расчетов по критерию Колмогорова
 
Разбиение на интервалы и подсчет количества попавших в интервал измерений хорошо подходит для гистограммы, но вносит существенную погрешность при работе с эмпирической функцией распределения вероятности. Предлагаю учитывать каждое измерение в отдельности при построении эмпирической функции. В доказательство приведу значения статистики Колмогорова с поправкой Большева для исходного способа расчета и для предлагаемого, а также соответствующие графики

**3.510 vs 1.848 (полноценный набор данных, погрешность 90%)**

![1](https://user-images.githubusercontent.com/55048058/137535977-fc2b7091-1c03-4fa8-8a04-2618e93e75dc.jpg)
![2](https://user-images.githubusercontent.com/55048058/137535983-35382551-b0ab-429c-a838-02fe5a62d50c.jpg)

**2.160 vs 0.751 (уменьшенный набор данных, погрешность 188%)**

![3](https://user-images.githubusercontent.com/55048058/137535994-61c1fbf2-1f92-4a3c-9617-0c012d127730.jpg)
![4](https://user-images.githubusercontent.com/55048058/137536004-a958d367-460a-4382-97fa-8c25bf8f74c3.jpg)

Исходный код в файле **cumulative_distribution.m**

```jsx
    v = sort(v);
    tmin = v(1);
    tmax = v(end);
    dt = (tmax - tmin) / m;
    
    f1 = zeros(length(t), 1);
    for i = 1 : length(t)
        if (t(i) < tmin)
            continue;
        end
        
        if (t(i) > tmax)
            f1(i) = 1;
            continue;
        end
        
        j = 1;
        while (t(i) > tmin + dt * j)
            j = j + 1;
        end
        
        f1(i) = sum(nu(1 : j)) / n;
        
    end
```
Предлагаемый код

```jsx
    v = sort(v);
    tmin = v(1);
    tmax = v(end);
    
    f1 = zeros(length(t), 1);
    for i = 1 : length(t)
        if (t(i) < tmin)
            continue;
        end
        
        if (t(i) > tmax)
            f1(i) = 1;
            continue;
        end
        
        f1(i) = size(v(v < t(i)), 1) / n; 
    end
```

**Comment by clever0ne** [comment]
> При тестах с моими исходными данными (см. приложение) в файле print_hystogram.m возникла ошибка в функции axis
> ```matlab
> figure('Name', 'Hystogram');
> plot(t, p1, 'r-', t, p2, 'b--');
> axis([tmin, tmax, 0, round(105 * max([p1', p2'])) / 100]);
> grid on;
> ```
> _Value must be a 1x2 vector of numeric type in which the second element is greater than the first element or is Inf._
> 
> В данном случае используется запись *axis([xmin xmax ymin ymax])*. Вероятно, что ошибка происходит при ymax <= ymin или round(105 * max([p1', p2'])) / 100] <= 0, т.е. функция round возвращает 0.
> 
> Предлагаю решение в виде масштабного коэффициента
> ```matlab
> figure('Name', 'Hystogram');
> plot(t, p1, 'r-', t, p2, 'b--');
> axis([tmin, tmax, 0, 1.1 * max([p1', p2'])]);
> grid on;
> ```
> Аналогичное исправление в файле print_cumulative_distribution_graph.m
> ```matlab
> figure('Name', 'Empirical Cumulative Distribution Function');
> plot(t, f1, 'r-', t, f2, 'b--');
> axis([tmin, tmax, 0, 1.1 * max([f1', f2'])]);
> grid on;
> ```

Предполагалось, что код вида `round(105 * max([p1', p2'])) / 100` позволит осуществлять округление вероятности до сотых, в связи с чем на графики функции плотности вероятности будет находиться целое число ячеек сетки. Однако, судя по всему, код работает неадекватно на выборках с большим объёмом. Попытаюсь исправить поведение программы в данном случае.

***

> Исходный код в файле check_kolmogorov_criterion.m
> ```matlab
> dn = max(abs(f1 - f2));
> lambda_1 = (6 * n * dn + 1) / (sqrt(6) * n);
> lambda_2 = sqrt(-log(alpha / 2) / 2);
> ```
> Оригинальная формула статистики Колмогорова с поправкой Большева
> ![image](https://user-images.githubusercontent.com/55034401/137549438-78421f49-f157-467e-8d54-a65daff375b0.png)

Несомненно, куда большая ошибка. Будет исправлена незамедлительно и безапелляционно.

***

> Разбиение на интервалы и подсчет количества попавших в интервал измерений хорошо подходит для гистограммы, но вносит существенную погрешность при работе с эмпирической функцией распределения вероятности. Предлагаю учитывать каждое измерение в отдельности при построении эмпирической функции. В доказательство приведу значения статистики Колмогорова с поправкой Большева для исходного способа расчета и для предлагаемого, а также соответствующие графики

На данный момент я уже получал устный фидбек от студента Жернакова. Дело в том, что существует несколько способов построения эмпирической функции распределения случайной величины, и в рамках курса "Высшей математики", а в частности — при выполнении расчётного задания по математической статистике, был реализован способ, аналогичный представленному. Однако же, вероятно, для проверки критерия значимости Колмогорова данный вариант действительно подходит куда в меньшей степени.

**Comment by clever0ne** [comment]
Замеченные ошибки предположительно исправлены и добавлены новые.
