### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by underbreathing** [clever0ne/laser_rangefinder#2]
@clever0ne  Привет! Слушай, я хотел спросить у тебя кое что по поводу курса "Цифровые устройства и микроконтроллеры" Можешь мне написать пожалуйста в вк: https://vk.com/0artichoke или скинь свою ссылку, я напишу

**Comment by clever0ne** [comment]
А причём _здесь_ этот курс? Это репозиторий с лабораторной работой по "Основам научных исследований, организации и планированию эксперимента".

**Comment by underbreathing** [comment]
Этот курс ни при чем, я просто в свежий написал
